# Generated by Django 3.2.7 on 2021-10-14 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pais',
            fields=[
                ('pais_id', models.AutoField(primary_key=True, serialize=False)),
                ('pais_nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('psn_id', models.AutoField(primary_key=True, serialize=False)),
                ('psn_docum_numero', models.IntegerField(default=0)),
                ('psn_nombres', models.CharField(max_length=50)),
                ('psn_apellidos', models.CharField(max_length=50)),
                ('psn_fecha_nto', models.DateTimeField(auto_now_add=True)),
                ('psn_genero', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='tipodoc',
            fields=[
                ('docum_tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('docum_tipo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='vacuna',
            fields=[
                ('vacuna_id', models.AutoField(primary_key=True, serialize=False)),
                ('vacuna_nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='vacunaacep',
            fields=[
                ('vacuna_aceptada_id', models.AutoField(primary_key=True, serialize=False)),
                ('pais_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_app.pais')),
                ('vacuna_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_app.vacuna')),
            ],
        ),
        migrations.CreateModel(
            name='solicitud',
            fields=[
                ('permiso_id', models.AutoField(primary_key=True, serialize=False)),
                ('permiso_fecha', models.DateTimeField(auto_now_add=True)),
                ('resultado_prueba', models.BooleanField(default=False)),
                ('permiso_autorizado', models.BooleanField(default=False)),
                ('pais_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_app.pais')),
                ('psn_cc_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_app.persona')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='docum_tipo_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_app.tipodoc'),
        ),
        migrations.AddField(
            model_name='persona',
            name='vacuna_aplicada_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_app.vacuna'),
        ),
    ]
