# Generated by Django 3.2.7 on 2021-10-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='psn_fecha_nto',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='permiso_fecha',
            field=models.DateField(),
        ),
    ]
